mutation {
  inventorySetQuantities(input: {name: "available", reason: "correction", ignoreCompareQuantity: true, quantities: [
      {inventoryItemId: "gid://shopify/InventoryItem/50182502744302", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182502809838", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182502842606", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182502875374", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182502908142", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182503432430", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182503465198", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182503530734", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182503563502", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182503629038", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182503661806", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182503694574", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182503760110", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182503792878", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182503825646", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182503858414", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182503891182", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182503923950", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182504546542", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182504579310", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182504612078", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182504644846", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182504677614", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182504710382", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182504743150", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182504775918", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182504808686", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182504841454", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182504874222", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182504906990", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182504939758", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182505005294", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182505038062", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182505070830", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182505103598", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182505136366", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182505169134", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182505201902", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182505234670", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182505267438", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182505300206", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182505332974", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182505365742", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182505398510", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182505431278", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182505464046", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182505496814", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182505529582", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182505562350", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182505758958", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182505791726", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182505824494", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182505857262", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182505890030", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182505922798", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182505955566", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182505988334", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182506021102", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182506053870", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182506119406", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182506152174", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182506184942", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182506217710", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182506250478", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182506414318", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182506447086", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182506479854", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182506512622", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182506578158", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182506610926", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182506643694", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182506676462", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182506709230", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182506741998", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182506774766", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182506807534", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182506840302", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182506905838", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182506938606", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182506971374", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182507004142", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182507036910", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182507102446", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182507135214", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182507167982", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182507200750", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182507233518", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182507266286", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182507299054", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182507364590", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182507397358", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182507430126", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182507462894", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182507528430", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182507561198", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182507593966", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182507626734", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182507659502", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182507692270", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182507725038", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182507757806", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182507790574", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182507823342", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182507856110", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182507888878", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182507954414", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182507987182", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182508019950", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182508052718", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182508085486", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182508151022", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182508183790", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182508216558", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182508249326", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182508282094", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182508314862", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182508347630", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182508380398", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182508413166", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182508445934", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182508478702", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182508511470", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182508544238", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182508577006", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182508642542", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182508839150", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182508871918", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182508937454", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182509002990", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182509035758", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182509068526", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182509101294", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182509134062", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182509166830", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182509199598", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182509232366", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182509265134", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182509297902", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182509330670", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182509363438", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182509396206", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182509428974", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182509461742", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182509527278", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182509592814", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182509625582", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182509658350", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182509691118", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182509723886", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182509756654", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182509789422", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182509822190", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182509854958", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182509887726", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182509920494", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182509953262", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182509986030", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182510018798", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182510051566", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182510084334", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182510215406", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182510248174", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182510313710", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182510346478", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182510379246", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182510412014", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182510444782", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182510477550", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182510510318", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182510575854", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182510608622", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182510641390", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182510674158", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182510706926", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182510739694", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182510772462", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182510837998", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182510870766", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182510903534", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182510969070", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182511001838", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182511034606", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182511067374", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182511100142", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182511132910", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182511165678", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182511198446", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182511231214", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182511263982", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182511296750", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182511329518", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182511362286", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182511395054", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182511427822", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182511460590", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182511657198", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182511689966", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182511722734", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182511755502", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182511788270", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182511821038", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182511853806", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182511886574", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182511919342", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182511952110", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182511984878", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182512017646", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182512050414", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182512083182", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182512115950", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182512181486", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182512214254", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182512247022", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182512279790", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182512312558", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182512345326", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182512378094", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182512541934", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182512574702", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182512607470", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182512640238", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182512673006", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182512705774", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182512738542", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182512771310", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182512804078", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182512836846", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182512869614", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182512902382", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182512935150", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182512967918", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182513000686", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182513033454", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182513066222", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182513098990", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182513131758", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182513164526", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182513230062", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182513262830", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182513295598", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182513328366", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182513361134", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182513393902", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182513426670", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182513459438", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182513524974", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182513590510", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182513623278", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182513688814", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182513754350", locationId: "gid://shopify/Location/81908531438", quantity: 50}
  ]}) {
    inventoryAdjustmentGroup { changes { delta } }
    userErrors { field message }
  }
}