mutation {
  inventorySetQuantities(input: {name: "available", reason: "correction", ignoreCompareQuantity: true, quantities: [
      {inventoryItemId: "gid://shopify/InventoryItem/50182513819886", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182513852654", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182513885422", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182513918190", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182513950958", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182513983726", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182514016494", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182514049262", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182514082030", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182514114798", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182514147566", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182514180334", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182514213102", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182514245870", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182514278638", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182514344174", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182514376942", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182514409710", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182514475246", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182514508014", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182514540782", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182514573550", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182514606318", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182514639086", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182514770158", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182514802926", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182514835694", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182514868462", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182514966766", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182514999534", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182515032302", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182515065070", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182515097838", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182515163374", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182515359982", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182515425518", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182515458286", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182515491054", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182515556590", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182515589358", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182515622126", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182515687662", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182515785966", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182515818734", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182515884270", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182515917038", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182515949806", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182516015342", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182516113646", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182516146414", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182516179182", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182516244718", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182516277486", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182516310254", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182516375790", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182516408558", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182516441326", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182516539630", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182516572398", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182516605166", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182516637934", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182516703470", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182516736238", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182516769006", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182516801774", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182516834542", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182516867310", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182516900078", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182516932846", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182517063918", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182517096686", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182517162222", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182517227758", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182517260526", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182517293294", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182517326062", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182517358830", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182517424366", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182518243566", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182518309102", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182518341870", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182518407406", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182518440174", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182518767854", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182518800622", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182518833390", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182518931694", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182518964462", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182518997230", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182519062766", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182519128302", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182519193838", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182519226606", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182519259374", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182519324910", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182519357678", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182519390446", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182519423214", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182519619822", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182519652590", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182519718126", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182519750894", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182519783662", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182519816430", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182519849198", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182519881966", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182519914734", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182519947502", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182519980270", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182520013038", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182520045806", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182520078574", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182520111342", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182520144110", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182520176878", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182520209646", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182520242414", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182520275182", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182520307950", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182520340718", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182520373486", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182520406254", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182520439022", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182520471790", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182520504558", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182520537326", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182520570094", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182520635630", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182520668398", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182520701166", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182520733934", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182520799470", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182520832238", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182520865006", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182520897774", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182520930542", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182520963310", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182520996078", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182521028846", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182521061614", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182521127150", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182521159918", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182521225454", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182521258222", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182521290990", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182521323758", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182521356526", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182521389294", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182521422062", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182521454830", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182521487598", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182521520366", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182521553134", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182521585902", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182521618670", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182521651438", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182521684206", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182521716974", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182521913582", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182521946350", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182521979118", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182522011886", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182522044654", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182522077422", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182522110190", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182522142958", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182522175726", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182522208494", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182522241262", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182522405102", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182522437870", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182522470638", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182522503406", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182522536174", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182522568942", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182522601710", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182522634478", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182522667246", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182522732782", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182522765550", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182522798318", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182523060462", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182523093230", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182523125998", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182523158766", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182523191534", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182523388142", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182523420910", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182523453678", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182523486446", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182523519214", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182523551982", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182523650286", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182523683054", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182523715822", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182523748590", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182523781358", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182523814126", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182523846894", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182523879662", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182523912430", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182523945198", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182523977966", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182524010734", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182524043502", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182524076270", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182524109038", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182524141806", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182524174574", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182524207342", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182524240110", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182524272878", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182524305646", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182524338414", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182524371182", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182524403950", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182524436718", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182524469486", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182524502254", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182524535022", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182524567790", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182524797166", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182524829934", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182524862702", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182524895470", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182524961006", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182525026542", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182525059310", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182525092078", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182525124846", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182525190382", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182525223150", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182525321454", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182525354222", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182525419758", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182525452526", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182525485294", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182525518062", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182525550830", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182525616366", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182525649134", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182525681902", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182525714670", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182525747438", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182525780206", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182525812974", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182525845742", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182525878510", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182525944046", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182525976814", locationId: "gid://shopify/Location/81908531438", quantity: 50}
  ]}) {
    inventoryAdjustmentGroup { changes { delta } }
    userErrors { field message }
  }
}