mutation {
  inventorySetQuantities(input: {name: "available", reason: "correction", ignoreCompareQuantity: true, quantities: [
      {inventoryItemId: "gid://shopify/InventoryItem/50182486229230", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182486294766", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182486393070", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182487605486", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182489637102", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182491078894", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182491177198", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182491996398", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182492029166", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182492061934", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182492094702", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182492356846", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182492389614", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182492422382", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182492553454", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182492586222", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182492618990", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182492651758", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182492684526", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182492717294", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182492750062", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182492782830", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182492815598", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182492848366", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182492881134", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182492913902", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182492946670", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182493012206", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182493044974", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182493077742", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182493110510", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182493143278", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182493176046", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182493208814", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182493241582", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182493274350", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182493307118", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182493339886", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182493372654", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182493405422", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182493438190", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182493470958", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182493503726", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182493536494", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182493602030", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182493634798", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182493667566", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182493700334", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182493733102", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182493765870", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182493798638", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182493831406", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182493864174", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182493896942", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182493929710", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182493962478", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182493995246", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182494028014", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182494060782", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182494093550", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182494126318", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182494159086", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182494191854", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182494224622", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182494257390", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182494290158", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182494322926", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182494355694", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182494388462", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182494421230", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182494453998", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182494650606", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182494683374", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182494716142", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182495142126", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182495174894", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182495207662", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182495240430", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182495273198", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182495305966", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182495338734", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182495371502", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182495404270", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182495437038", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182495469806", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182495502574", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182495535342", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182495568110", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182495600878", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182495633646", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182495666414", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182495699182", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182495731950", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182495764718", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182495797486", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182495830254", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182495895790", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182495928558", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182495994094", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182496026862", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182496059630", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182496092398", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182496125166", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182496157934", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182496190702", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182496223470", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182496256238", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182496289006", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182496321774", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182496354542", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182496387310", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182496420078", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182496452846", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182496485614", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182496518382", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182496551150", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182496583918", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182496616686", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182496682222", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182496747758", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182496780526", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182496846062", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182496911598", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182496944366", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182496977134", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182497042670", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182497075438", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182497140974", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182497173742", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182497206510", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182497239278", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182497272046", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182497337582", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182497370350", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182497403118", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182497435886", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182497468654", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182497501422", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182497534190", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182497566958", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182497599726", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182497632494", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182497665262", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182497698030", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182497763566", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182497927406", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182498058478", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182498156782", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182498189550", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182498222318", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182498255086", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182498287854", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182498320622", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182498517230", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182498582766", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182498615534", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182498648302", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182498681070", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182498713838", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182498746606", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182498779374", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182498812142", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182498844910", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182498877678", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182498910446", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182498943214", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182499008750", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182499107054", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182499172590", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182499238126", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182499303662", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182499369198", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182499434734", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182499467502", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182499500270", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182499533038", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182499565806", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182499598574", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182499664110", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182499696878", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182499729646", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182499762414", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182499795182", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182499827950", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182499860718", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182499893486", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182499926254", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182499991790", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182500024558", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182500090094", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182500122862", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182500155630", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182500188398", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182500221166", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182500253934", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182500286702", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182500319470", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182500385006", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182500417774", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182500450542", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182500483310", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182500516078", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182500548846", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182500581614", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182500614382", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182500647150", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182500712686", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182500745454", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182500810990", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182500843758", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182500876526", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182500909294", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182500942062", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182500974830", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182501007598", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182501040366", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182501073134", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182501105902", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182501138670", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182501171438", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182501204206", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182501236974", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182501269742", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182501302510", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182501335278", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182501368046", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182501400814", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182501433582", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182501499118", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182501531886", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182501728494", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182501794030", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182501957870", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182502023406", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182502088942", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182502121710", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182502154478", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182502187246", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182502220014", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182502285550", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182502318318", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182502351086", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182502383854", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182502416622", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182502449390", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182502482158", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182502547694", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182502580462", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182502645998", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182502711534", locationId: "gid://shopify/Location/81908531438", quantity: 50}
  ]}) {
    inventoryAdjustmentGroup { changes { delta } }
    userErrors { field message }
  }
}