mutation {
  inventorySetQuantities(input: {name: "available", reason: "correction", ignoreCompareQuantity: true, quantities: [
      {inventoryItemId: "gid://shopify/InventoryItem/50182473941230", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182473973998", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182474006766", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182474039534", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182474105070", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182474137838", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182474170606", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182474236142", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182474268910", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182474301678", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182474334446", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182474367214", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182474399982", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182474432750", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182474465518", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182474498286", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182474531054", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182474563822", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182474596590", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182474629358", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182474662126", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182474694894", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182474727662", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182474760430", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182474793198", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182474825966", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182474858734", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182474891502", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182474924270", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182475120878", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182475153646", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182475186414", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182475219182", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182475251950", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182475284718", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182475317486", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182475350254", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182475383022", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182475415790", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182475448558", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182475481326", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182475514094", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182475546862", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182475579630", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182475612398", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182475677934", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182475710702", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182475743470", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182475776238", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182475841774", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182475874542", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182475940078", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182475972846", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182476005614", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182476169454", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182476202222", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182476234990", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182476267758", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182476333294", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182476366062", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182476398830", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182476431598", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182476464366", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182476628206", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182476660974", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182476693742", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182476726510", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182476759278", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182476792046", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182476824814", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182476857582", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182476890350", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182476923118", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182477742318", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182477775086", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182477807854", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182477840622", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182477873390", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182477906158", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182477938926", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182477971694", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182478168302", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182478201070", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182478233838", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182478266606", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182478299374", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182478332142", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182478364910", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182478397678", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182478528750", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182478561518", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182478594286", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182478627054", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182478659822", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182478692590", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182478725358", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182478790894", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182479118574", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182479151342", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182479184110", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182479249646", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182479282414", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182479315182", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182479347950", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182479380718", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182479413486", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182479446254", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182479479022", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182479511790", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182479544558", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182479577326", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182479610094", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182479642862", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182479675630", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182479708398", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182479773934", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182479806702", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182479839470", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182479872238", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182479937774", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182479970542", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182480003310", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182480036078", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182480101614", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182480167150", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182480396526", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182480429294", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182480462062", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182480494830", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182480527598", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182480560366", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182480593134", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182480625902", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182480658670", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182480691438", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182480724206", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182480756974", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182480789742", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182480822510", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182480855278", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182480888046", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182480920814", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182480953582", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182480986350", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182481019118", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182481051886", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182481248494", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182481281262", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182481314030", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182481346798", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182481379566", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182481412334", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182481445102", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182481510638", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182481543406", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182481576174", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182481707246", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182481805550", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182481838318", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182481903854", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182481936622", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182481969390", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182482034926", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182482133230", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182482165998", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182482198766", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182482231534", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182482264302", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182482297070", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182482329838", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182482362606", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182482395374", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182482428142", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182482493678", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182482559214", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182482591982", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182482624750", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182482657518", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182482690286", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182482723054", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182482755822", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182482854126", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182482985198", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182483017966", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182483050734", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182483083502", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182483116270", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182483149038", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182483181806", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182483214574", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182483280110", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182483345646", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182483378414", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182483443950", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182483509486", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182483575022", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182483706094", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182483738862", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182483837166", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182483869934", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182483902702", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182483935470", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182484001006", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182484066542", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182484099310", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182484132078", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182484197614", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182484328686", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182484394222", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182484426990", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182484459758", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182484492526", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182484525294", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182484558062", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182484590830", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182484623598", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182484951278", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182484984046", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182485016814", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182485049582", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182485082350", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182485115118", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182485147886", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182485180654", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182485213422", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182485246190", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182485278958", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182485311726", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182485344494", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182485377262", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182485410030", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182485442798", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182485475566", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182485541102", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182485573870", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182485606638", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182485639406", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182485704942", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182485770478", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182485803246", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182485836014", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182485868782", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182485901550", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182485934318", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182485967086", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182485999854", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182486065390", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182486098158", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182486130926", locationId: "gid://shopify/Location/81908531438", quantity: 50}
      {inventoryItemId: "gid://shopify/InventoryItem/50182486163694", locationId: "gid://shopify/Location/81908531438", quantity: 50}
  ]}) {
    inventoryAdjustmentGroup { changes { delta } }
    userErrors { field message }
  }
}