mutation {
  t0: inventoryItemUpdate(id: "gid://shopify/InventoryItem/50182473941230", input: {tracked: true}) { inventoryItem { id } userErrors { field message } }
  t1: inventoryItemUpdate(id: "gid://shopify/InventoryItem/50182473973998", input: {tracked: true}) { inventoryItem { id } userErrors { field message } }
  t2: inventoryItemUpdate(id: "gid://shopify/InventoryItem/50182474006766", input: {tracked: true}) { inventoryItem { id } userErrors { field message } }
  t3: inventoryItemUpdate(id: "gid://shopify/InventoryItem/50182474039534", input: {tracked: true}) { inventoryItem { id } userErrors { field message } }
  t4: inventoryItemUpdate(id: "gid://shopify/InventoryItem/50182474105070", input: {tracked: true}) { inventoryItem { id } userErrors { field message } }
  t5: inventoryItemUpdate(id: "gid://shopify/InventoryItem/50182474137838", input: {tracked: true}) { inventoryItem { id } userErrors { field message } }
  t6: inventoryItemUpdate(id: "gid://shopify/InventoryItem/50182474170606", input: {tracked: true}) { inventoryItem { id } userErrors { field message } }
  t7: inventoryItemUpdate(id: "gid://shopify/InventoryItem/50182474236142", input: {tracked: true}) { inventoryItem { id } userErrors { field message } }
  t8: inventoryItemUpdate(id: "gid://shopify/InventoryItem/50182474268910", input: {tracked: true}) { inventoryItem { id } userErrors { field message } }
  t9: inventoryItemUpdate(id: "gid://shopify/InventoryItem/50182474301678", input: {tracked: true}) { inventoryItem { id } userErrors { field message } }
  t10: inventoryItemUpdate(id: "gid://shopify/InventoryItem/50182474334446", input: {tracked: true}) { inventoryItem { id } userErrors { field message } }
  t11: inventoryItemUpdate(id: "gid://shopify/InventoryItem/50182474367214", input: {tracked: true}) { inventoryItem { id } userErrors { field message } }
  t12: inventoryItemUpdate(id: "gid://shopify/InventoryItem/50182474399982", input: {tracked: true}) { inventoryItem { id } userErrors { field message } }
  t13: inventoryItemUpdate(id: "gid://shopify/InventoryItem/50182474432750", input: {tracked: true}) { inventoryItem { id } userErrors { field message } }
  t14: inventoryItemUpdate(id: "gid://shopify/InventoryItem/50182474465518", input: {tracked: true}) { inventoryItem { id } userErrors { field message } }
  t15: inventoryItemUpdate(id: "gid://shopify/InventoryItem/50182474498286", input: {tracked: true}) { inventoryItem { id } userErrors { field message } }
  t16: inventoryItemUpdate(id: "gid://shopify/InventoryItem/50182474531054", input: {tracked: true}) { inventoryItem { id } userErrors { field message } }
  t17: inventoryItemUpdate(id: "gid://shopify/InventoryItem/50182474563822", input: {tracked: true}) { inventoryItem { id } userErrors { field message } }
  t18: inventoryItemUpdate(id: "gid://shopify/InventoryItem/50182474596590", input: {tracked: true}) { inventoryItem { id } userErrors { field message } }
  t19: inventoryItemUpdate(id: "gid://shopify/InventoryItem/50182474629358", input: {tracked: true}) { inventoryItem { id } userErrors { field message } }
  t20: inventoryItemUpdate(id: "gid://shopify/InventoryItem/50182474662126", input: {tracked: true}) { inventoryItem { id } userErrors { field message } }
  t21: inventoryItemUpdate(id: "gid://shopify/InventoryItem/50182474694894", input: {tracked: true}) { inventoryItem { id } userErrors { field message } }
  t22: inventoryItemUpdate(id: "gid://shopify/InventoryItem/50182474727662", input: {tracked: true}) { inventoryItem { id } userErrors { field message } }
  t23: inventoryItemUpdate(id: "gid://shopify/InventoryItem/50182474760430", input: {tracked: true}) { inventoryItem { id } userErrors { field message } }
  t24: inventoryItemUpdate(id: "gid://shopify/InventoryItem/50182474793198", input: {tracked: true}) { inventoryItem { id } userErrors { field message } }
  t25: inventoryItemUpdate(id: "gid://shopify/InventoryItem/50182474825966", input: {tracked: true}) { inventoryItem { id } userErrors { field message } }
  t26: inventoryItemUpdate(id: "gid://shopify/InventoryItem/50182474858734", input: {tracked: true}) { inventoryItem { id } userErrors { field message } }
  t27: inventoryItemUpdate(id: "gid://shopify/InventoryItem/50182474891502", input: {tracked: true}) { inventoryItem { id } userErrors { field message } }
  t28: inventoryItemUpdate(id: "gid://shopify/InventoryItem/50182474924270", input: {tracked: true}) { inventoryItem { id } userErrors { field message } }
  t29: inventoryItemUpdate(id: "gid://shopify/InventoryItem/50182475120878", input: {tracked: true}) { inventoryItem { id } userErrors { field message } }
  t30: inventoryItemUpdate(id: "gid://shopify/InventoryItem/50182475153646", input: {tracked: true}) { inventoryItem { id } userErrors { field message } }
  t31: inventoryItemUpdate(id: "gid://shopify/InventoryItem/50182475186414", input: {tracked: true}) { inventoryItem { id } userErrors { field message } }
  t32: inventoryItemUpdate(id: "gid://shopify/InventoryItem/50182475219182", input: {tracked: true}) { inventoryItem { id } userErrors { field message } }
  t33: inventoryItemUpdate(id: "gid://shopify/InventoryItem/50182475251950", input: {tracked: true}) { inventoryItem { id } userErrors { field message } }
  t34: inventoryItemUpdate(id: "gid://shopify/InventoryItem/50182475284718", input: {tracked: true}) { inventoryItem { id } userErrors { field message } }
  t35: inventoryItemUpdate(id: "gid://shopify/InventoryItem/50182475317486", input: {tracked: true}) { inventoryItem { id } userErrors { field message } }
  t36: inventoryItemUpdate(id: "gid://shopify/InventoryItem/50182475350254", input: {tracked: true}) { inventoryItem { id } userErrors { field message } }
  t37: inventoryItemUpdate(id: "gid://shopify/InventoryItem/50182475383022", input: {tracked: true}) { inventoryItem { id } userErrors { field message } }
  t38: inventoryItemUpdate(id: "gid://shopify/InventoryItem/50182475415790", input: {tracked: true}) { inventoryItem { id } userErrors { field message } }
  t39: inventoryItemUpdate(id: "gid://shopify/InventoryItem/50182475448558", input: {tracked: true}) { inventoryItem { id } userErrors { field message } }
  t40: inventoryItemUpdate(id: "gid://shopify/InventoryItem/50182475481326", input: {tracked: true}) { inventoryItem { id } userErrors { field message } }
  t41: inventoryItemUpdate(id: "gid://shopify/InventoryItem/50182475514094", input: {tracked: true}) { inventoryItem { id } userErrors { field message } }
  t42: inventoryItemUpdate(id: "gid://shopify/InventoryItem/50182475546862", input: {tracked: true}) { inventoryItem { id } userErrors { field message } }
  t43: inventoryItemUpdate(id: "gid://shopify/InventoryItem/50182475579630", input: {tracked: true}) { inventoryItem { id } userErrors { field message } }
  t44: inventoryItemUpdate(id: "gid://shopify/InventoryItem/50182475612398", input: {tracked: true}) { inventoryItem { id } userErrors { field message } }
  t45: inventoryItemUpdate(id: "gid://shopify/InventoryItem/50182475677934", input: {tracked: true}) { inventoryItem { id } userErrors { field message } }
  t46: inventoryItemUpdate(id: "gid://shopify/InventoryItem/50182475710702", input: {tracked: true}) { inventoryItem { id } userErrors { field message } }
  t47: inventoryItemUpdate(id: "gid://shopify/InventoryItem/50182475743470", input: {tracked: true}) { inventoryItem { id } userErrors { field message } }
  t48: inventoryItemUpdate(id: "gid://shopify/InventoryItem/50182475776238", input: {tracked: true}) { inventoryItem { id } userErrors { field message } }
  t49: inventoryItemUpdate(id: "gid://shopify/InventoryItem/50182475841774", input: {tracked: true}) { inventoryItem { id } userErrors { field message } }
}