mutation {
  t0: inventoryItemUpdate(id: "gid://shopify/InventoryItem/50202968031470", input: {tracked: true}) { inventoryItem { id } userErrors { field message } }
  t1: inventoryItemUpdate(id: "gid://shopify/InventoryItem/50202968064238", input: {tracked: true}) { inventoryItem { id } userErrors { field message } }
  t2: inventoryItemUpdate(id: "gid://shopify/InventoryItem/50202968097006", input: {tracked: true}) { inventoryItem { id } userErrors { field message } }
  t3: inventoryItemUpdate(id: "gid://shopify/InventoryItem/50202968162542", input: {tracked: true}) { inventoryItem { id } userErrors { field message } }
  t4: inventoryItemUpdate(id: "gid://shopify/InventoryItem/50202968195310", input: {tracked: true}) { inventoryItem { id } userErrors { field message } }
  t5: inventoryItemUpdate(id: "gid://shopify/InventoryItem/50202968228078", input: {tracked: true}) { inventoryItem { id } userErrors { field message } }
  t6: inventoryItemUpdate(id: "gid://shopify/InventoryItem/50202968293614", input: {tracked: true}) { inventoryItem { id } userErrors { field message } }
  t7: inventoryItemUpdate(id: "gid://shopify/InventoryItem/50202968883438", input: {tracked: true}) { inventoryItem { id } userErrors { field message } }
  t8: inventoryItemUpdate(id: "gid://shopify/InventoryItem/50202968916206", input: {tracked: true}) { inventoryItem { id } userErrors { field message } }
  t9: inventoryItemUpdate(id: "gid://shopify/InventoryItem/50202968948974", input: {tracked: true}) { inventoryItem { id } userErrors { field message } }
  t10: inventoryItemUpdate(id: "gid://shopify/InventoryItem/50202968981742", input: {tracked: true}) { inventoryItem { id } userErrors { field message } }
  t11: inventoryItemUpdate(id: "gid://shopify/InventoryItem/50202969047278", input: {tracked: true}) { inventoryItem { id } userErrors { field message } }
  t12: inventoryItemUpdate(id: "gid://shopify/InventoryItem/50202969080046", input: {tracked: true}) { inventoryItem { id } userErrors { field message } }
  t13: inventoryItemUpdate(id: "gid://shopify/InventoryItem/50202969112814", input: {tracked: true}) { inventoryItem { id } userErrors { field message } }
  t14: inventoryItemUpdate(id: "gid://shopify/InventoryItem/50202969211118", input: {tracked: true}) { inventoryItem { id } userErrors { field message } }
  t15: inventoryItemUpdate(id: "gid://shopify/InventoryItem/50202969243886", input: {tracked: true}) { inventoryItem { id } userErrors { field message } }
  t16: inventoryItemUpdate(id: "gid://shopify/InventoryItem/50202969276654", input: {tracked: true}) { inventoryItem { id } userErrors { field message } }
  t17: inventoryItemUpdate(id: "gid://shopify/InventoryItem/50202969342190", input: {tracked: true}) { inventoryItem { id } userErrors { field message } }
  t18: inventoryItemUpdate(id: "gid://shopify/InventoryItem/50202969374958", input: {tracked: true}) { inventoryItem { id } userErrors { field message } }
  t19: inventoryItemUpdate(id: "gid://shopify/InventoryItem/50202969440494", input: {tracked: true}) { inventoryItem { id } userErrors { field message } }
  t20: inventoryItemUpdate(id: "gid://shopify/InventoryItem/50202969473262", input: {tracked: true}) { inventoryItem { id } userErrors { field message } }
  t21: inventoryItemUpdate(id: "gid://shopify/InventoryItem/50202969506030", input: {tracked: true}) { inventoryItem { id } userErrors { field message } }
  t22: inventoryItemUpdate(id: "gid://shopify/InventoryItem/50202969604334", input: {tracked: true}) { inventoryItem { id } userErrors { field message } }
  t23: inventoryItemUpdate(id: "gid://shopify/InventoryItem/50202969669870", input: {tracked: true}) { inventoryItem { id } userErrors { field message } }
  t24: inventoryItemUpdate(id: "gid://shopify/InventoryItem/50202969800942", input: {tracked: true}) { inventoryItem { id } userErrors { field message } }
  t25: inventoryItemUpdate(id: "gid://shopify/InventoryItem/50202969833710", input: {tracked: true}) { inventoryItem { id } userErrors { field message } }
  t26: inventoryItemUpdate(id: "gid://shopify/InventoryItem/50202969866478", input: {tracked: true}) { inventoryItem { id } userErrors { field message } }
  t27: inventoryItemUpdate(id: "gid://shopify/InventoryItem/50202969899246", input: {tracked: true}) { inventoryItem { id } userErrors { field message } }
  t28: inventoryItemUpdate(id: "gid://shopify/InventoryItem/50202969932014", input: {tracked: true}) { inventoryItem { id } userErrors { field message } }
  t29: inventoryItemUpdate(id: "gid://shopify/InventoryItem/50202970095854", input: {tracked: true}) { inventoryItem { id } userErrors { field message } }
  t30: inventoryItemUpdate(id: "gid://shopify/InventoryItem/50202970194158", input: {tracked: true}) { inventoryItem { id } userErrors { field message } }
  t31: inventoryItemUpdate(id: "gid://shopify/InventoryItem/50202970259694", input: {tracked: true}) { inventoryItem { id } userErrors { field message } }
  t32: inventoryItemUpdate(id: "gid://shopify/InventoryItem/50202970292462", input: {tracked: true}) { inventoryItem { id } userErrors { field message } }
  t33: inventoryItemUpdate(id: "gid://shopify/InventoryItem/50202970325230", input: {tracked: true}) { inventoryItem { id } userErrors { field message } }
  t34: inventoryItemUpdate(id: "gid://shopify/InventoryItem/50202970357998", input: {tracked: true}) { inventoryItem { id } userErrors { field message } }
  t35: inventoryItemUpdate(id: "gid://shopify/InventoryItem/50202970456302", input: {tracked: true}) { inventoryItem { id } userErrors { field message } }
  t36: inventoryItemUpdate(id: "gid://shopify/InventoryItem/50202970489070", input: {tracked: true}) { inventoryItem { id } userErrors { field message } }
  t37: inventoryItemUpdate(id: "gid://shopify/InventoryItem/50202970587374", input: {tracked: true}) { inventoryItem { id } userErrors { field message } }
  t38: inventoryItemUpdate(id: "gid://shopify/InventoryItem/50202970620142", input: {tracked: true}) { inventoryItem { id } userErrors { field message } }
  t39: inventoryItemUpdate(id: "gid://shopify/InventoryItem/50202970751214", input: {tracked: true}) { inventoryItem { id } userErrors { field message } }
  t40: inventoryItemUpdate(id: "gid://shopify/InventoryItem/50202970849518", input: {tracked: true}) { inventoryItem { id } userErrors { field message } }
  t41: inventoryItemUpdate(id: "gid://shopify/InventoryItem/50202970882286", input: {tracked: true}) { inventoryItem { id } userErrors { field message } }
  t42: inventoryItemUpdate(id: "gid://shopify/InventoryItem/50202970915054", input: {tracked: true}) { inventoryItem { id } userErrors { field message } }
  t43: inventoryItemUpdate(id: "gid://shopify/InventoryItem/50202970947822", input: {tracked: true}) { inventoryItem { id } userErrors { field message } }
  t44: inventoryItemUpdate(id: "gid://shopify/InventoryItem/50202970980590", input: {tracked: true}) { inventoryItem { id } userErrors { field message } }
  t45: inventoryItemUpdate(id: "gid://shopify/InventoryItem/50202971013358", input: {tracked: true}) { inventoryItem { id } userErrors { field message } }
  t46: inventoryItemUpdate(id: "gid://shopify/InventoryItem/50202971046126", input: {tracked: true}) { inventoryItem { id } userErrors { field message } }
  t47: inventoryItemUpdate(id: "gid://shopify/InventoryItem/50202971701486", input: {tracked: true}) { inventoryItem { id } userErrors { field message } }
  t48: inventoryItemUpdate(id: "gid://shopify/InventoryItem/50202971734254", input: {tracked: true}) { inventoryItem { id } userErrors { field message } }
  t49: inventoryItemUpdate(id: "gid://shopify/InventoryItem/50202971767022", input: {tracked: true}) { inventoryItem { id } userErrors { field message } }
}