mutation {
  t0: inventoryItemUpdate(id: "gid://shopify/InventoryItem/50182481379566", input: {tracked: true}) { inventoryItem { id } userErrors { field message } }
  t1: inventoryItemUpdate(id: "gid://shopify/InventoryItem/50182481412334", input: {tracked: true}) { inventoryItem { id } userErrors { field message } }
  t2: inventoryItemUpdate(id: "gid://shopify/InventoryItem/50182481445102", input: {tracked: true}) { inventoryItem { id } userErrors { field message } }
  t3: inventoryItemUpdate(id: "gid://shopify/InventoryItem/50182481510638", input: {tracked: true}) { inventoryItem { id } userErrors { field message } }
  t4: inventoryItemUpdate(id: "gid://shopify/InventoryItem/50182481543406", input: {tracked: true}) { inventoryItem { id } userErrors { field message } }
  t5: inventoryItemUpdate(id: "gid://shopify/InventoryItem/50182481576174", input: {tracked: true}) { inventoryItem { id } userErrors { field message } }
  t6: inventoryItemUpdate(id: "gid://shopify/InventoryItem/50182481707246", input: {tracked: true}) { inventoryItem { id } userErrors { field message } }
  t7: inventoryItemUpdate(id: "gid://shopify/InventoryItem/50182481805550", input: {tracked: true}) { inventoryItem { id } userErrors { field message } }
  t8: inventoryItemUpdate(id: "gid://shopify/InventoryItem/50182481838318", input: {tracked: true}) { inventoryItem { id } userErrors { field message } }
  t9: inventoryItemUpdate(id: "gid://shopify/InventoryItem/50182481903854", input: {tracked: true}) { inventoryItem { id } userErrors { field message } }
  t10: inventoryItemUpdate(id: "gid://shopify/InventoryItem/50182481936622", input: {tracked: true}) { inventoryItem { id } userErrors { field message } }
  t11: inventoryItemUpdate(id: "gid://shopify/InventoryItem/50182481969390", input: {tracked: true}) { inventoryItem { id } userErrors { field message } }
  t12: inventoryItemUpdate(id: "gid://shopify/InventoryItem/50182482034926", input: {tracked: true}) { inventoryItem { id } userErrors { field message } }
  t13: inventoryItemUpdate(id: "gid://shopify/InventoryItem/50182482133230", input: {tracked: true}) { inventoryItem { id } userErrors { field message } }
  t14: inventoryItemUpdate(id: "gid://shopify/InventoryItem/50182482165998", input: {tracked: true}) { inventoryItem { id } userErrors { field message } }
  t15: inventoryItemUpdate(id: "gid://shopify/InventoryItem/50182482198766", input: {tracked: true}) { inventoryItem { id } userErrors { field message } }
  t16: inventoryItemUpdate(id: "gid://shopify/InventoryItem/50182482231534", input: {tracked: true}) { inventoryItem { id } userErrors { field message } }
  t17: inventoryItemUpdate(id: "gid://shopify/InventoryItem/50182482264302", input: {tracked: true}) { inventoryItem { id } userErrors { field message } }
  t18: inventoryItemUpdate(id: "gid://shopify/InventoryItem/50182482297070", input: {tracked: true}) { inventoryItem { id } userErrors { field message } }
  t19: inventoryItemUpdate(id: "gid://shopify/InventoryItem/50182482329838", input: {tracked: true}) { inventoryItem { id } userErrors { field message } }
  t20: inventoryItemUpdate(id: "gid://shopify/InventoryItem/50182482362606", input: {tracked: true}) { inventoryItem { id } userErrors { field message } }
  t21: inventoryItemUpdate(id: "gid://shopify/InventoryItem/50182482395374", input: {tracked: true}) { inventoryItem { id } userErrors { field message } }
  t22: inventoryItemUpdate(id: "gid://shopify/InventoryItem/50182482428142", input: {tracked: true}) { inventoryItem { id } userErrors { field message } }
  t23: inventoryItemUpdate(id: "gid://shopify/InventoryItem/50182482493678", input: {tracked: true}) { inventoryItem { id } userErrors { field message } }
  t24: inventoryItemUpdate(id: "gid://shopify/InventoryItem/50182482559214", input: {tracked: true}) { inventoryItem { id } userErrors { field message } }
  t25: inventoryItemUpdate(id: "gid://shopify/InventoryItem/50182482591982", input: {tracked: true}) { inventoryItem { id } userErrors { field message } }
  t26: inventoryItemUpdate(id: "gid://shopify/InventoryItem/50182482624750", input: {tracked: true}) { inventoryItem { id } userErrors { field message } }
  t27: inventoryItemUpdate(id: "gid://shopify/InventoryItem/50182482657518", input: {tracked: true}) { inventoryItem { id } userErrors { field message } }
  t28: inventoryItemUpdate(id: "gid://shopify/InventoryItem/50182482690286", input: {tracked: true}) { inventoryItem { id } userErrors { field message } }
  t29: inventoryItemUpdate(id: "gid://shopify/InventoryItem/50182482723054", input: {tracked: true}) { inventoryItem { id } userErrors { field message } }
  t30: inventoryItemUpdate(id: "gid://shopify/InventoryItem/50182482755822", input: {tracked: true}) { inventoryItem { id } userErrors { field message } }
  t31: inventoryItemUpdate(id: "gid://shopify/InventoryItem/50182482854126", input: {tracked: true}) { inventoryItem { id } userErrors { field message } }
  t32: inventoryItemUpdate(id: "gid://shopify/InventoryItem/50182482985198", input: {tracked: true}) { inventoryItem { id } userErrors { field message } }
  t33: inventoryItemUpdate(id: "gid://shopify/InventoryItem/50182483017966", input: {tracked: true}) { inventoryItem { id } userErrors { field message } }
  t34: inventoryItemUpdate(id: "gid://shopify/InventoryItem/50182483050734", input: {tracked: true}) { inventoryItem { id } userErrors { field message } }
  t35: inventoryItemUpdate(id: "gid://shopify/InventoryItem/50182483083502", input: {tracked: true}) { inventoryItem { id } userErrors { field message } }
  t36: inventoryItemUpdate(id: "gid://shopify/InventoryItem/50182483116270", input: {tracked: true}) { inventoryItem { id } userErrors { field message } }
  t37: inventoryItemUpdate(id: "gid://shopify/InventoryItem/50182483149038", input: {tracked: true}) { inventoryItem { id } userErrors { field message } }
  t38: inventoryItemUpdate(id: "gid://shopify/InventoryItem/50182483181806", input: {tracked: true}) { inventoryItem { id } userErrors { field message } }
  t39: inventoryItemUpdate(id: "gid://shopify/InventoryItem/50182483214574", input: {tracked: true}) { inventoryItem { id } userErrors { field message } }
  t40: inventoryItemUpdate(id: "gid://shopify/InventoryItem/50182483280110", input: {tracked: true}) { inventoryItem { id } userErrors { field message } }
  t41: inventoryItemUpdate(id: "gid://shopify/InventoryItem/50182483345646", input: {tracked: true}) { inventoryItem { id } userErrors { field message } }
  t42: inventoryItemUpdate(id: "gid://shopify/InventoryItem/50182483378414", input: {tracked: true}) { inventoryItem { id } userErrors { field message } }
  t43: inventoryItemUpdate(id: "gid://shopify/InventoryItem/50182483443950", input: {tracked: true}) { inventoryItem { id } userErrors { field message } }
  t44: inventoryItemUpdate(id: "gid://shopify/InventoryItem/50182483509486", input: {tracked: true}) { inventoryItem { id } userErrors { field message } }
  t45: inventoryItemUpdate(id: "gid://shopify/InventoryItem/50182483575022", input: {tracked: true}) { inventoryItem { id } userErrors { field message } }
  t46: inventoryItemUpdate(id: "gid://shopify/InventoryItem/50182483706094", input: {tracked: true}) { inventoryItem { id } userErrors { field message } }
  t47: inventoryItemUpdate(id: "gid://shopify/InventoryItem/50182483738862", input: {tracked: true}) { inventoryItem { id } userErrors { field message } }
  t48: inventoryItemUpdate(id: "gid://shopify/InventoryItem/50182483837166", input: {tracked: true}) { inventoryItem { id } userErrors { field message } }
  t49: inventoryItemUpdate(id: "gid://shopify/InventoryItem/50182483869934", input: {tracked: true}) { inventoryItem { id } userErrors { field message } }
}