mutation {
  t0: inventoryItemUpdate(id: "gid://shopify/InventoryItem/50182505791726", input: {tracked: true}) { inventoryItem { id } userErrors { field message } }
  t1: inventoryItemUpdate(id: "gid://shopify/InventoryItem/50182505824494", input: {tracked: true}) { inventoryItem { id } userErrors { field message } }
  t2: inventoryItemUpdate(id: "gid://shopify/InventoryItem/50182505857262", input: {tracked: true}) { inventoryItem { id } userErrors { field message } }
  t3: inventoryItemUpdate(id: "gid://shopify/InventoryItem/50182505890030", input: {tracked: true}) { inventoryItem { id } userErrors { field message } }
  t4: inventoryItemUpdate(id: "gid://shopify/InventoryItem/50182505922798", input: {tracked: true}) { inventoryItem { id } userErrors { field message } }
  t5: inventoryItemUpdate(id: "gid://shopify/InventoryItem/50182505955566", input: {tracked: true}) { inventoryItem { id } userErrors { field message } }
  t6: inventoryItemUpdate(id: "gid://shopify/InventoryItem/50182505988334", input: {tracked: true}) { inventoryItem { id } userErrors { field message } }
  t7: inventoryItemUpdate(id: "gid://shopify/InventoryItem/50182506021102", input: {tracked: true}) { inventoryItem { id } userErrors { field message } }
  t8: inventoryItemUpdate(id: "gid://shopify/InventoryItem/50182506053870", input: {tracked: true}) { inventoryItem { id } userErrors { field message } }
  t9: inventoryItemUpdate(id: "gid://shopify/InventoryItem/50182506119406", input: {tracked: true}) { inventoryItem { id } userErrors { field message } }
  t10: inventoryItemUpdate(id: "gid://shopify/InventoryItem/50182506152174", input: {tracked: true}) { inventoryItem { id } userErrors { field message } }
  t11: inventoryItemUpdate(id: "gid://shopify/InventoryItem/50182506184942", input: {tracked: true}) { inventoryItem { id } userErrors { field message } }
  t12: inventoryItemUpdate(id: "gid://shopify/InventoryItem/50182506217710", input: {tracked: true}) { inventoryItem { id } userErrors { field message } }
  t13: inventoryItemUpdate(id: "gid://shopify/InventoryItem/50182506250478", input: {tracked: true}) { inventoryItem { id } userErrors { field message } }
  t14: inventoryItemUpdate(id: "gid://shopify/InventoryItem/50182506414318", input: {tracked: true}) { inventoryItem { id } userErrors { field message } }
  t15: inventoryItemUpdate(id: "gid://shopify/InventoryItem/50182506447086", input: {tracked: true}) { inventoryItem { id } userErrors { field message } }
  t16: inventoryItemUpdate(id: "gid://shopify/InventoryItem/50182506479854", input: {tracked: true}) { inventoryItem { id } userErrors { field message } }
  t17: inventoryItemUpdate(id: "gid://shopify/InventoryItem/50182506512622", input: {tracked: true}) { inventoryItem { id } userErrors { field message } }
  t18: inventoryItemUpdate(id: "gid://shopify/InventoryItem/50182506578158", input: {tracked: true}) { inventoryItem { id } userErrors { field message } }
  t19: inventoryItemUpdate(id: "gid://shopify/InventoryItem/50182506610926", input: {tracked: true}) { inventoryItem { id } userErrors { field message } }
  t20: inventoryItemUpdate(id: "gid://shopify/InventoryItem/50182506643694", input: {tracked: true}) { inventoryItem { id } userErrors { field message } }
  t21: inventoryItemUpdate(id: "gid://shopify/InventoryItem/50182506676462", input: {tracked: true}) { inventoryItem { id } userErrors { field message } }
  t22: inventoryItemUpdate(id: "gid://shopify/InventoryItem/50182506709230", input: {tracked: true}) { inventoryItem { id } userErrors { field message } }
  t23: inventoryItemUpdate(id: "gid://shopify/InventoryItem/50182506741998", input: {tracked: true}) { inventoryItem { id } userErrors { field message } }
  t24: inventoryItemUpdate(id: "gid://shopify/InventoryItem/50182506774766", input: {tracked: true}) { inventoryItem { id } userErrors { field message } }
  t25: inventoryItemUpdate(id: "gid://shopify/InventoryItem/50182506807534", input: {tracked: true}) { inventoryItem { id } userErrors { field message } }
  t26: inventoryItemUpdate(id: "gid://shopify/InventoryItem/50182506840302", input: {tracked: true}) { inventoryItem { id } userErrors { field message } }
  t27: inventoryItemUpdate(id: "gid://shopify/InventoryItem/50182506905838", input: {tracked: true}) { inventoryItem { id } userErrors { field message } }
  t28: inventoryItemUpdate(id: "gid://shopify/InventoryItem/50182506938606", input: {tracked: true}) { inventoryItem { id } userErrors { field message } }
  t29: inventoryItemUpdate(id: "gid://shopify/InventoryItem/50182506971374", input: {tracked: true}) { inventoryItem { id } userErrors { field message } }
  t30: inventoryItemUpdate(id: "gid://shopify/InventoryItem/50182507004142", input: {tracked: true}) { inventoryItem { id } userErrors { field message } }
  t31: inventoryItemUpdate(id: "gid://shopify/InventoryItem/50182507036910", input: {tracked: true}) { inventoryItem { id } userErrors { field message } }
  t32: inventoryItemUpdate(id: "gid://shopify/InventoryItem/50182507102446", input: {tracked: true}) { inventoryItem { id } userErrors { field message } }
  t33: inventoryItemUpdate(id: "gid://shopify/InventoryItem/50182507135214", input: {tracked: true}) { inventoryItem { id } userErrors { field message } }
  t34: inventoryItemUpdate(id: "gid://shopify/InventoryItem/50182507167982", input: {tracked: true}) { inventoryItem { id } userErrors { field message } }
  t35: inventoryItemUpdate(id: "gid://shopify/InventoryItem/50182507200750", input: {tracked: true}) { inventoryItem { id } userErrors { field message } }
  t36: inventoryItemUpdate(id: "gid://shopify/InventoryItem/50182507233518", input: {tracked: true}) { inventoryItem { id } userErrors { field message } }
  t37: inventoryItemUpdate(id: "gid://shopify/InventoryItem/50182507266286", input: {tracked: true}) { inventoryItem { id } userErrors { field message } }
  t38: inventoryItemUpdate(id: "gid://shopify/InventoryItem/50182507299054", input: {tracked: true}) { inventoryItem { id } userErrors { field message } }
  t39: inventoryItemUpdate(id: "gid://shopify/InventoryItem/50182507364590", input: {tracked: true}) { inventoryItem { id } userErrors { field message } }
  t40: inventoryItemUpdate(id: "gid://shopify/InventoryItem/50182507397358", input: {tracked: true}) { inventoryItem { id } userErrors { field message } }
  t41: inventoryItemUpdate(id: "gid://shopify/InventoryItem/50182507430126", input: {tracked: true}) { inventoryItem { id } userErrors { field message } }
  t42: inventoryItemUpdate(id: "gid://shopify/InventoryItem/50182507462894", input: {tracked: true}) { inventoryItem { id } userErrors { field message } }
  t43: inventoryItemUpdate(id: "gid://shopify/InventoryItem/50182507528430", input: {tracked: true}) { inventoryItem { id } userErrors { field message } }
  t44: inventoryItemUpdate(id: "gid://shopify/InventoryItem/50182507561198", input: {tracked: true}) { inventoryItem { id } userErrors { field message } }
  t45: inventoryItemUpdate(id: "gid://shopify/InventoryItem/50182507593966", input: {tracked: true}) { inventoryItem { id } userErrors { field message } }
  t46: inventoryItemUpdate(id: "gid://shopify/InventoryItem/50182507626734", input: {tracked: true}) { inventoryItem { id } userErrors { field message } }
  t47: inventoryItemUpdate(id: "gid://shopify/InventoryItem/50182507659502", input: {tracked: true}) { inventoryItem { id } userErrors { field message } }
  t48: inventoryItemUpdate(id: "gid://shopify/InventoryItem/50182507692270", input: {tracked: true}) { inventoryItem { id } userErrors { field message } }
  t49: inventoryItemUpdate(id: "gid://shopify/InventoryItem/50182507725038", input: {tracked: true}) { inventoryItem { id } userErrors { field message } }
}