mutation {
  t0: inventoryItemUpdate(id: "gid://shopify/InventoryItem/50182523912430", input: {tracked: true}) { inventoryItem { id } userErrors { field message } }
  t1: inventoryItemUpdate(id: "gid://shopify/InventoryItem/50182523945198", input: {tracked: true}) { inventoryItem { id } userErrors { field message } }
  t2: inventoryItemUpdate(id: "gid://shopify/InventoryItem/50182523977966", input: {tracked: true}) { inventoryItem { id } userErrors { field message } }
  t3: inventoryItemUpdate(id: "gid://shopify/InventoryItem/50182524010734", input: {tracked: true}) { inventoryItem { id } userErrors { field message } }
  t4: inventoryItemUpdate(id: "gid://shopify/InventoryItem/50182524043502", input: {tracked: true}) { inventoryItem { id } userErrors { field message } }
  t5: inventoryItemUpdate(id: "gid://shopify/InventoryItem/50182524076270", input: {tracked: true}) { inventoryItem { id } userErrors { field message } }
  t6: inventoryItemUpdate(id: "gid://shopify/InventoryItem/50182524109038", input: {tracked: true}) { inventoryItem { id } userErrors { field message } }
  t7: inventoryItemUpdate(id: "gid://shopify/InventoryItem/50182524141806", input: {tracked: true}) { inventoryItem { id } userErrors { field message } }
  t8: inventoryItemUpdate(id: "gid://shopify/InventoryItem/50182524174574", input: {tracked: true}) { inventoryItem { id } userErrors { field message } }
  t9: inventoryItemUpdate(id: "gid://shopify/InventoryItem/50182524207342", input: {tracked: true}) { inventoryItem { id } userErrors { field message } }
  t10: inventoryItemUpdate(id: "gid://shopify/InventoryItem/50182524240110", input: {tracked: true}) { inventoryItem { id } userErrors { field message } }
  t11: inventoryItemUpdate(id: "gid://shopify/InventoryItem/50182524272878", input: {tracked: true}) { inventoryItem { id } userErrors { field message } }
  t12: inventoryItemUpdate(id: "gid://shopify/InventoryItem/50182524305646", input: {tracked: true}) { inventoryItem { id } userErrors { field message } }
  t13: inventoryItemUpdate(id: "gid://shopify/InventoryItem/50182524338414", input: {tracked: true}) { inventoryItem { id } userErrors { field message } }
  t14: inventoryItemUpdate(id: "gid://shopify/InventoryItem/50182524371182", input: {tracked: true}) { inventoryItem { id } userErrors { field message } }
  t15: inventoryItemUpdate(id: "gid://shopify/InventoryItem/50182524403950", input: {tracked: true}) { inventoryItem { id } userErrors { field message } }
  t16: inventoryItemUpdate(id: "gid://shopify/InventoryItem/50182524436718", input: {tracked: true}) { inventoryItem { id } userErrors { field message } }
  t17: inventoryItemUpdate(id: "gid://shopify/InventoryItem/50182524469486", input: {tracked: true}) { inventoryItem { id } userErrors { field message } }
  t18: inventoryItemUpdate(id: "gid://shopify/InventoryItem/50182524502254", input: {tracked: true}) { inventoryItem { id } userErrors { field message } }
  t19: inventoryItemUpdate(id: "gid://shopify/InventoryItem/50182524535022", input: {tracked: true}) { inventoryItem { id } userErrors { field message } }
  t20: inventoryItemUpdate(id: "gid://shopify/InventoryItem/50182524567790", input: {tracked: true}) { inventoryItem { id } userErrors { field message } }
  t21: inventoryItemUpdate(id: "gid://shopify/InventoryItem/50182524797166", input: {tracked: true}) { inventoryItem { id } userErrors { field message } }
  t22: inventoryItemUpdate(id: "gid://shopify/InventoryItem/50182524829934", input: {tracked: true}) { inventoryItem { id } userErrors { field message } }
  t23: inventoryItemUpdate(id: "gid://shopify/InventoryItem/50182524862702", input: {tracked: true}) { inventoryItem { id } userErrors { field message } }
  t24: inventoryItemUpdate(id: "gid://shopify/InventoryItem/50182524895470", input: {tracked: true}) { inventoryItem { id } userErrors { field message } }
  t25: inventoryItemUpdate(id: "gid://shopify/InventoryItem/50182524961006", input: {tracked: true}) { inventoryItem { id } userErrors { field message } }
  t26: inventoryItemUpdate(id: "gid://shopify/InventoryItem/50182525026542", input: {tracked: true}) { inventoryItem { id } userErrors { field message } }
  t27: inventoryItemUpdate(id: "gid://shopify/InventoryItem/50182525059310", input: {tracked: true}) { inventoryItem { id } userErrors { field message } }
  t28: inventoryItemUpdate(id: "gid://shopify/InventoryItem/50182525092078", input: {tracked: true}) { inventoryItem { id } userErrors { field message } }
  t29: inventoryItemUpdate(id: "gid://shopify/InventoryItem/50182525124846", input: {tracked: true}) { inventoryItem { id } userErrors { field message } }
  t30: inventoryItemUpdate(id: "gid://shopify/InventoryItem/50182525190382", input: {tracked: true}) { inventoryItem { id } userErrors { field message } }
  t31: inventoryItemUpdate(id: "gid://shopify/InventoryItem/50182525223150", input: {tracked: true}) { inventoryItem { id } userErrors { field message } }
  t32: inventoryItemUpdate(id: "gid://shopify/InventoryItem/50182525321454", input: {tracked: true}) { inventoryItem { id } userErrors { field message } }
  t33: inventoryItemUpdate(id: "gid://shopify/InventoryItem/50182525354222", input: {tracked: true}) { inventoryItem { id } userErrors { field message } }
  t34: inventoryItemUpdate(id: "gid://shopify/InventoryItem/50182525419758", input: {tracked: true}) { inventoryItem { id } userErrors { field message } }
  t35: inventoryItemUpdate(id: "gid://shopify/InventoryItem/50182525452526", input: {tracked: true}) { inventoryItem { id } userErrors { field message } }
  t36: inventoryItemUpdate(id: "gid://shopify/InventoryItem/50182525485294", input: {tracked: true}) { inventoryItem { id } userErrors { field message } }
  t37: inventoryItemUpdate(id: "gid://shopify/InventoryItem/50182525518062", input: {tracked: true}) { inventoryItem { id } userErrors { field message } }
  t38: inventoryItemUpdate(id: "gid://shopify/InventoryItem/50182525550830", input: {tracked: true}) { inventoryItem { id } userErrors { field message } }
  t39: inventoryItemUpdate(id: "gid://shopify/InventoryItem/50182525616366", input: {tracked: true}) { inventoryItem { id } userErrors { field message } }
  t40: inventoryItemUpdate(id: "gid://shopify/InventoryItem/50182525649134", input: {tracked: true}) { inventoryItem { id } userErrors { field message } }
  t41: inventoryItemUpdate(id: "gid://shopify/InventoryItem/50182525681902", input: {tracked: true}) { inventoryItem { id } userErrors { field message } }
  t42: inventoryItemUpdate(id: "gid://shopify/InventoryItem/50182525714670", input: {tracked: true}) { inventoryItem { id } userErrors { field message } }
  t43: inventoryItemUpdate(id: "gid://shopify/InventoryItem/50182525747438", input: {tracked: true}) { inventoryItem { id } userErrors { field message } }
  t44: inventoryItemUpdate(id: "gid://shopify/InventoryItem/50182525780206", input: {tracked: true}) { inventoryItem { id } userErrors { field message } }
  t45: inventoryItemUpdate(id: "gid://shopify/InventoryItem/50182525812974", input: {tracked: true}) { inventoryItem { id } userErrors { field message } }
  t46: inventoryItemUpdate(id: "gid://shopify/InventoryItem/50182525845742", input: {tracked: true}) { inventoryItem { id } userErrors { field message } }
  t47: inventoryItemUpdate(id: "gid://shopify/InventoryItem/50182525878510", input: {tracked: true}) { inventoryItem { id } userErrors { field message } }
  t48: inventoryItemUpdate(id: "gid://shopify/InventoryItem/50182525944046", input: {tracked: true}) { inventoryItem { id } userErrors { field message } }
  t49: inventoryItemUpdate(id: "gid://shopify/InventoryItem/50182525976814", input: {tracked: true}) { inventoryItem { id } userErrors { field message } }
}